version: '3'
services:
    topedges:
        container_name: topedges-database
        build: .
        ports:
            - 9000:80
        volumes:
            - ./mysql-data:/var/lib/mysql
    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: topedges-db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
